USE [W_GnBD]
ALTER INDEX ALL ON USERLOGIN
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESS
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSARGUMENT
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONEMAILSIGNATURE
REBUILD;
ALTER INDEX ALL ON NOTIFICATIONMESSAGE
REBUILD;
ALTER INDEX ALL ON ASYNCPROCESSATTACHMENTS
REBUILD;
ALTER INDEX ALL ON USERAUTHORIZATION
REBUILD;
ALTER INDEX ALL ON PRJPLAYER
REBUILD;
ALTER INDEX ALL ON PRJPLAYER_TEAM
REBUILD;
ALTER INDEX ALL ON PRJSKILL
REBUILD;
ALTER INDEX ALL ON PRJSTATS
REBUILD;
ALTER INDEX ALL ON PRJTEAM
REBUILD;
ALTER INDEX ALL ON PRJSKILL_PLAYER
REBUILD;
GO